name: Release Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python-version: 3.9

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Step 4: Build the Python package
      - name: Build the package
        run: python -m build .

      # Step 5: Extract the filename of the built package
      - name: Get built wheel filename
        id: get_filename
        run: |
          FILE=$(ls dist/*.whl)
          echo "Found file: $FILE"
          echo "FILENAME=$(basename $FILE)" >> $GITHUB_ENV

      # Step 6: Upload wheels to GitHub Release
      - name: Upload built packages to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ env.FILENAME }}
          token: ${{ secrets.PAC_TOKEN }}